package models

import (
	"encoding/json"
	"time"
)

// EventType categorizes network occurrences
type EventType string

const (
	EventDNS      EventType = "DNS"
	EventPortScan EventType = "PORT_SCAN"
	EventARP      EventType = "ARP"
	EventPhysical EventType = "PHYSICAL"
	EventAlert    EventType = "THREAT_ALERT"
	EventProxy    EventType = "PROXY"
	EventVM         EventType = "VM"
	EventCompliance EventType = "COMPLIANCE"
)

// NetworkEvent represents an observation generated by an intelligence module.
//
// Per ADR-0062 every event leaving the pipeline carries an Ed25519
// signature over its canonical bytes. The signature is computed by
// internal/events.Signer using a pki.PurposeEventSigning keypair;
// verification is the symmetric operation in internal/events.Verifier.
// Spectre/Cerebro consumers fetch the public key by SignerKeyID from
// the JWKS endpoint at /.well-known/jwks.json.
//
// Signature and SignerKeyID are `omitempty` so unsigned events round-
// trip through JSON cleanly (test fixtures, in-process intermediates
// before the publish hook). Production consumers reject unsigned events.
type NetworkEvent struct {
	ID          string         `json:"id"`
	Type        EventType      `json:"type"`
	Source      string         `json:"source"`
	Destination string         `json:"destination"`
	Metadata    map[string]any `json:"metadata"`
	Timestamp   time.Time      `json:"timestamp"`

	// ── ADR-0062: cryptographic provenance ──
	Signature   []byte `json:"sig,omitempty"`
	SignerKeyID string `json:"kid,omitempty"`
}

// CanonicalBytes returns the deterministic byte string used as the
// signing surface for an event. The Signature and SignerKeyID fields
// are zeroed before serialization so the canonical form is identical
// at sign-time and verify-time regardless of which side observed it.
//
// Encoding is `encoding/json.Marshal` of the struct without the
// signature fields. Go's json package emits keys alphabetically and
// stable-sorts maps by key since Go 1.12, which is enough determinism
// for OWASAKA's controlled producer-consumer pair. A future hardening
// (Sprint 7 supply chain) may swap this for RFC 8785 JCS once
// heterogeneous consumers exist.
func (e NetworkEvent) CanonicalBytes() ([]byte, error) {
	signable := e
	signable.Signature = nil
	signable.SignerKeyID = ""
	return json.Marshal(signable)
}

// IsSigned reports whether the event carries both a non-empty Signature
// and a non-empty SignerKeyID. Use as a precondition before passing to
// a Verifier; unsigned events are valid in dev but rejected in prod.
func (e NetworkEvent) IsSigned() bool {
	return len(e.Signature) > 0 && e.SignerKeyID != ""
}
