package correlation

import (
	"math"
	"strings"
	"time"
	"unicode"

	"github.com/google/uuid"
	"github.com/marcosfpina/O.W.A.S.A.K.A/internal/models"
)

// Rule represents an abstract threat detection signature (heuristic or Sigma-based)
type Rule interface {
	Name() string
	Evaluate(event models.NetworkEvent) *models.NetworkEvent
}

// DefaultRules returns Go-native rules that require logic beyond static YAML field matching.
// YAML-based detection rules are embedded in the binary and loaded by NewEngine automatically.
func DefaultRules() []Rule {
	return []Rule{
		&DGADetectionRule{EntropyThreshold: 3.8, MinLength: 10},
	}
}

// DGADetectionRule detects domain names generated by Domain Generation Algorithms.
// DGA domains have high Shannon entropy and low consonant/vowel ratio, which static
// YAML field matching cannot express.
type DGADetectionRule struct {
	EntropyThreshold float64
	MinLength        int
}

func (r *DGADetectionRule) Name() string { return "DGA_DOMAIN_DETECTED" }

func (r *DGADetectionRule) Evaluate(e models.NetworkEvent) *models.NetworkEvent {
	if e.Type != models.EventDNS {
		return nil
	}
	name, ok := e.Metadata["name"].(string)
	if !ok || len(name) < r.MinLength {
		return nil
	}

	// Extract the second-level domain (leftmost label) for analysis.
	labels := strings.Split(strings.TrimSuffix(name, "."), ".")
	if len(labels) < 2 {
		return nil
	}
	label := labels[0]
	if len(label) < r.MinLength {
		return nil
	}

	entropy := shannonEntropy(label)
	if entropy < r.EntropyThreshold {
		return nil
	}

	// Additional signal: very low vowel ratio (random strings have fewer vowels).
	vowelRatio := float64(countVowels(label)) / float64(len(label))
	if vowelRatio > 0.38 {
		return nil
	}

	return &models.NetworkEvent{
		ID:          uuid.NewString(),
		Type:        models.EventAlert,
		Timestamp:   time.Now().UTC(),
		Source:      "CorrelationEngine",
		Destination: e.Source,
		Metadata: map[string]any{
			"rule":        r.Name(),
			"description": "DNS query to high-entropy domain consistent with DGA-generated C2",
			"severity":    "HIGH",
			"trigger_id":  e.ID,
			"domain":      name,
			"label":       label,
			"entropy":     entropy,
			"vowel_ratio": vowelRatio,
		},
	}
}

func shannonEntropy(s string) float64 {
	if len(s) == 0 {
		return 0
	}
	freq := make(map[rune]int)
	for _, c := range s {
		freq[c]++
	}
	n := float64(len(s))
	var h float64
	for _, count := range freq {
		p := float64(count) / n
		h -= p * math.Log2(p)
	}
	return h
}

func countVowels(s string) int {
	vowels := "aeiouAEIOU"
	n := 0
	for _, c := range s {
		if unicode.IsLetter(c) && strings.ContainsRune(vowels, c) {
			n++
		}
	}
	return n
}
